apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: airbyte-vs
  namespace: deus
spec:
  gateways:
  - istio-system/https-internal
  hosts:
  - airbyteus.dev.quadpay.internal
  http:
  - name: slash
    match: 
    - uri: 
        prefix: /
    route:
    - destination:
        port: 
          number: 80
        host: airbyte-us-airbyte-webapp-svc
