apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: airbyte-destination-rule
  namespace: deus
spec:
  host: airbyte-us-airbyte-webapp-svc.deus.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: airbyte-vs
  namespace: deus
spec:
  gateways:
    - istio-system/https-internal
  hosts:
    - airbyte.dev.us.quadpay.io
  http:
    - match:
        - uri:
            prefix: /
      name: slash
      route:
        - destination:
            host: airbyte-us-airbyte-webapp-svc.deus.svc.cluster.local
            port:
              number: 80
